#  docker-compose up -d
services:
  redis:
    image: redis:7.0
    container_name: items-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  minio:
    image: minio/minio
    container_name: items-photos
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Automatyczne tworzenie bucketu w MinIO
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing local/items-photos;
      /usr/bin/mc anonymous set public local/items-photos;
      exit 0;
      "

volumes:
  minio_data:
