auth:
  limits:
    AUTH_LOGIN:
      capacity: 15
      refill: 10
      duration: PT1M

    AUTH_REGISTER:
      capacity: 6
      refill: 3
      duration: PT5M

    AUTH_LOGOUT:
      capacity: 20
      refill: 20
      duration: PT1M

    AUTH_FREE:
      capacity: 150
      refill: 75
      duration: PT1M

    TWO_FACTOR_FREE:
      capacity: 40
      refill: 20
      duration: PT5M

    TWO_FACTOR_VERIFY:
      capacity: 20
      refill: 10
      duration: PT5M

    TWO_FACTOR_STRICT:
      capacity: 10
      refill: 5
      duration: PT5M

    USER_ACTION_FREE:
      capacity: 300
      refill: 150
      duration: PT2M
